name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/checkout@v2 
      - name: Build & Deploy
      
        run: |
          echo "${{ secrets.KEY }}" > private_key.pem
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@ec2-44-203-100-59.compute-1.amazonaws.com

              # Now we have got the access of EC2 and we will start the deploy .
              cd /home/ubuntu/littleangryunicorn &&
              git pull
